homework_done_count = 12
spent_time = 1.5
name_of_course = "Phyton"
time_of_one_task = (spent_time/homework_done_count)
a = homework_done_count
b = spent_time
c = name_of_course
d = time_of_one_task
print("Курс",":",c,"," "всего задач",":",a,','"затрачено часов",":",b,',',"среднее выполнения задания"' ',d,'.',sep='')